### ISSUE TITLE
✅ Keep default rules

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#187]
## Overview

* Keep default rules

## Overview
    
    * Add intent error file of `xxxxxx`
    
    * See https://eslint.org/docs/latest/rules/xxxxxx
    
    ## Default
    
    ```
      xxxxxx:
        - error
    ```

    ## Setting

    * ✅ Keep it

    ```
      xxxxxx:
        - error
    ```

## Tasks

- [x] #35
- [x] #109
- [x] #126
- [x] #155
- [ ] 🛠 Add intent rule file of `block-scoped-var`
- [ ] 🛠 Add intent rule file of `block-spacing`
- [x] #153
- [ ] 🛠 Add intent rule file of `camelcase`
- [x] #37
- [ ] 🛠 Add intent rule file of `comma-spacing`
- [ ] 🛠 Add intent rule file of `comma-style`
- [ ] 🛠 Add intent rule file of `computed-property-spacing`
- [ ] 🛠 Add intent rule file of `consistent-this`
- [ ] 🛠 Add intent rule file of `constructor-super`
- [ ] 🛠 Add intent rule file of `curly`
- [ ] 🛠 Add intent rule file of `default-case`
- [ ] 🛠 Add intent rule file of `default-case-last`
- [ ] 🛠 Add intent rule file of `default-param-last`
- [x] #122
- [ ] 🛠 Add intent rule file of `eqeqeq`
- [ ] 🛠 Add intent rule file of `func-call-spacing`
- [ ] 🛠 Add intent rule file of `func-name-matching`
- [ ] 🛠 Add intent rule file of `getter-return`
- [ ] 🛠 Add intent rule file of `id-length`
- [ ] 🛠 Add intent rule file of `init-declarations`
- [ ] 🛠 Add intent rule file of `jsx-quotes`
- [ ] 🛠 Add intent rule file of `key-spacing`
- [ ] 🛠 Add intent rule file of `keyword-spacing`
- [ ] 🛠 Add intent rule file of `linebreak-style`
- [ ] 🛠 Add intent rule file of `lines-between-class-members`
- [ ] 🛠 Add intent rule file of `logical-assignment-operators`
- [ ] 🛠 Add intent rule file of `max-depth`
- [ ] 🛠 Add intent rule file of `max-nested-callbacks`
- [ ] 🛠 Add intent rule file of `max-statements-per-line`
- [ ] 🛠 Add intent rule file of `multiline-ternary`
- [ ] 🛠 Add intent rule file of `new-cap`
- [ ] 🛠 Add intent rule file of `new-parens`
- [ ] 🛠 Add intent rule file of `no-alert`
- [ ] 🛠 Add intent rule file of `no-array-constructor`
- [ ] 🛠 Add intent rule file of `no-async-promise-executor`
- [ ] 🛠 Add intent rule file of `no-await-in-loop`
- [ ] 🛠 Add intent rule file of `no-caller`
- [ ] 🛠 Add intent rule file of `no-case-declarations`
- [ ] 🛠 Add intent rule file of `no-class-assign`
- [ ] 🛠 Add intent rule file of `no-compare-neg-zero`
- [ ] 🛠 Add intent rule file of `no-cond-assign`
- [x] #259
- [ ] 🛠 Add intent rule file of `no-console`
- [ ] 🛠 Add intent rule file of `no-const-assign`
- [ ] 🛠 Add intent rule file of `no-constant-binary-expression`
- [ ] 🛠 Add intent rule file of `no-constant-condition`
- [ ] 🛠 Add intent rule file of `no-constructor-return`
- [x] #169
- [ ] 🛠 Add intent rule file of `no-debugger`
- [ ] 🛠 Add intent rule file of `no-delete-var`
- [ ] 🛠 Add intent rule file of `no-div-regex`
- [ ] 🛠 Add intent rule file of `no-dupe-args`
- [ ] 🛠 Add intent rule file of `no-dupe-class-members`
- [ ] 🛠 Add intent rule file of `no-dupe-else-if`
- [ ] 🛠 Add intent rule file of `no-dupe-keys`
- [ ] 🛠 Add intent rule file of `no-duplicate-case`
- [ ] 🛠 Add intent rule file of `no-duplicate-imports`
- [ ] 🛠 Add intent rule file of `no-else-return`
- [x] #149
- [ ] 🛠 Add intent rule file of `no-empty-character-class`
- [ ] 🛠 Add intent rule file of `no-empty-pattern`
- [ ] 🛠 Add intent rule file of `no-eq-null`
- [ ] 🛠 Add intent rule file of `no-eval`
- [ ] 🛠 Add intent rule file of `no-ex-assign`
- [ ] 🛠 Add intent rule file of `no-extend-native`
- [ ] 🛠 Add intent rule file of `no-extra-bind`
- [ ] 🛠 Add intent rule file of `no-extra-label`
- [ ] 🛠 Add intent rule file of `no-extra-semi`
- [ ] 🛠 Add intent rule file of `no-fallthrough`
- [ ] 🛠 Add intent rule file of `no-floating-decimal`
- [ ] 🛠 Add intent rule file of `no-func-assign`
- [x] #261
- [ ] 🛠 Add intent rule file of `no-implicit-globals`
- [ ] 🛠 Add intent rule file of `no-implied-eval`
- [ ] 🛠 Add intent rule file of `no-import-assign`
- [ ] 🛠 Add intent rule file of `no-inner-declarations`
- [ ] 🛠 Add intent rule file of `no-invalid-regexp`
- [ ] 🛠 Add intent rule file of `no-invalid-this`
- [ ] 🛠 Add intent rule file of `no-iterator`
- [ ] 🛠 Add intent rule file of `no-label-var`
- [ ] 🛠 Add intent rule file of `no-labels`
- [ ] 🛠 Add intent rule file of `no-lonely-if`
- [ ] 🛠 Add intent rule file of `no-loop-func`
- [ ] 🛠 Add intent rule file of `no-loss-of-precision`
- [ ] 🛠 Add intent rule file of `no-misleading-character-class`
- [x] #266
- [ ] 🛠 Add intent rule file of `no-mixed-spaces-and-tabs`
- [ ] 🛠 Add intent rule file of `no-multi-assign`
- [ ] 🛠 Add intent rule file of `no-multi-spaces`
- [ ] 🛠 Add intent rule file of `no-multi-str`
- [ ] 🛠 Add intent rule file of `no-negated-condition`
- [ ] 🛠 Add intent rule file of `no-nested-ternary`
- [ ] 🛠 Add intent rule file of `no-new`
- [ ] 🛠 Add intent rule file of `no-new-func`
- [ ] 🛠 Add intent rule file of `no-new-object`
- [ ] 🛠 Add intent rule file of `no-new-symbol`
- [ ] 🛠 Add intent rule file of `no-new-wrappers`
- [ ] 🛠 Add intent rule file of `no-nonoctal-decimal-escape`
- [ ] 🛠 Add intent rule file of `no-obj-calls`
- [ ] 🛠 Add intent rule file of `no-octal`
- [ ] 🛠 Add intent rule file of `no-octal-escape`
- [ ] 🛠 Add intent rule file of `no-plusplus`
- [ ] 🛠 Add intent rule file of `no-promise-executor-return`
- [ ] 🛠 Add intent rule file of `no-proto`
- [ ] 🛠 Add intent rule file of `no-prototype-builtins`
- [ ] 🛠 Add intent rule file of `no-redeclare`
- [ ] 🛠 Add intent rule file of `no-regex-spaces`
- [ ] 🛠 Add intent rule file of `no-restricted-exports`
- [ ] 🛠 Add intent rule file of `no-restricted-globals`
- [ ] 🛠 Add intent rule file of `no-restricted-imports`
- [ ] 🛠 Add intent rule file of `no-return-assign`
- [ ] 🛠 Add intent rule file of `no-return-await`
- [ ] 🛠 Add intent rule file of `no-script-url`
- [ ] 🛠 Add intent rule file of `no-self-assign`
- [ ] 🛠 Add intent rule file of `no-self-compare`
- [ ] 🛠 Add intent rule file of `no-sequences`
- [ ] 🛠 Add intent rule file of `no-setter-return`
- [ ] 🛠 Add intent rule file of `no-shadow-restricted-names`
- [ ] 🛠 Add intent rule file of `no-sparse-arrays`
- [ ] 🛠 Add intent rule file of `no-tabs`
- [ ] 🛠 Add intent rule file of `no-template-curly-in-string`
- [ ] 🛠 Add intent rule file of `no-this-before-super`
- [ ] 🛠 Add intent rule file of `no-throw-literal`
- [ ] 🛠 Add intent rule file of `no-trailing-spaces`
- [x] #268
- [ ] 🛠 Add intent rule file of `no-undef-init`
- [ ] 🛠 Add intent rule file of `no-unexpected-multiline`
- [ ] 🛠 Add intent rule file of `no-unmodified-loop-condition`
- [ ] 🛠 Add intent rule file of `no-unreachable`
- [ ] 🛠 Add intent rule file of `no-unreachable-loop`
- [ ] 🛠 Add intent rule file of `no-unsafe-finally`
- [ ] 🛠 Add intent rule file of `no-unsafe-negation`
- [ ] 🛠 Add intent rule file of `no-unused-expressions`
- [ ] 🛠 Add intent rule file of `no-unused-labels`
- [ ] 🛠 Add intent rule file of `no-unused-private-class-members`
- [x] #280
- [ ] 🛠 Add intent rule file of `no-useless-backreference`
- [ ] 🛠 Add intent rule file of `no-useless-call`
- [ ] 🛠 Add intent rule file of `no-useless-catch`
- [ ] 🛠 Add intent rule file of `no-useless-computed-key`
- [ ] 🛠 Add intent rule file of `no-useless-concat`
- [ ] 🛠 Add intent rule file of `no-useless-constructor`
- [ ] 🛠 Add intent rule file of `no-useless-escape`
- [ ] 🛠 Add intent rule file of `no-useless-rename`
- [ ] 🛠 Add intent rule file of `no-useless-return`
- [ ] 🛠 Add intent rule file of `no-var`
- [ ] 🛠 Add intent rule file of `no-void`
- [ ] 🛠 Add intent rule file of `no-warning-comments`
- [ ] 🛠 Add intent rule file of `no-whitespace-before-property`
- [ ] 🛠 Add intent rule file of `no-with`
- [ ] 🛠 Add intent rule file of `nonblock-statement-body-position`
- [x] #272
- [ ] 🛠 Add intent rule file of `one-var-declaration-per-line`
- [ ] 🛠 Add intent rule file of `operator-assignment`
- [ ] 🛠 Add intent rule file of `prefer-arrow-callback`
- [ ] 🛠 Add intent rule file of `prefer-const`
- [x] #278
- [ ] 🛠 Add intent rule file of `prefer-exponentiation-operator`
- [x] #178
- [ ] 🛠 Add intent rule file of `prefer-object-has-own`
- [ ] 🛠 Add intent rule file of `prefer-object-spread`
- [ ] 🛠 Add intent rule file of `prefer-promise-reject-errors`
- [ ] 🛠 Add intent rule file of `prefer-regex-literals`
- [ ] 🛠 Add intent rule file of `prefer-rest-params`
- [ ] 🛠 Add intent rule file of `prefer-spread`
- [x] #133
- [ ] 🛠 Add intent rule file of `require-atomic-updates`
- [ ] 🛠 Add intent rule file of `require-await`
- [x] #485
- [ ] 🛠 Add intent rule file of `require-yield`
- [ ] 🛠 Add intent rule file of `rest-spread-spacing`
- [ ] 🛠 Add intent rule file of `semi-spacing`
- [ ] 🛠 Add intent rule file of `sort-imports`
- [x] #274
- [x] #276
- [ ] 🛠 Add intent rule file of `space-in-parens`
- [ ] 🛠 Add intent rule file of `space-infix-ops`
- [ ] 🛠 Add intent rule file of `space-unary-ops`
- [ ] 🛠 Add intent rule file of `strict`
- [ ] 🛠 Add intent rule file of `switch-colon-spacing`
- [ ] 🛠 Add intent rule file of `symbol-description`
- [ ] 🛠 Add intent rule file of `template-curly-spacing`
- [ ] 🛠 Add intent rule file of `unicode-bom`
- [ ] 🛠 Add intent rule file of `valid-typeof`
- [ ] 🛠 Add intent rule file of `vars-on-top`
- [ ] 🛠 Add intent rule file of `yoda`
