### ISSUE TITLE
⚙️ Install Jest

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#19]
## Overview

* Install Jest.

## Procedure

* Run in terminal

```
npm install --save-dev \
    jest \
    @types/jest
```

## Tasks

- [x] Install Jest and concerning modules.
- [x] Add `jest.confg.js`.
- [x] Add sample test.
- [x] Add test script into `package.json`.
