### ISSUE TITLE
🛠 Fulfill ESLint test structure

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#24]
## Overview

* Fulfill ESLint test structure.

* Create prototype test structure for initialized standard rules.

## Tasks

- [ ] Consider ESLint test structure. (at comment of this issue)
- [ ] Add test of standard rule `indent`.
- [ ] Add test of standard rule `quotes`.
- [ ] Add test of standard rule `semi`.
