### ISSUE TITLE
💪 Remove unnecessary options from `no-restricted-properties`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#347]
## Overview

* `jest/no-disabled-tests` があれば、`no-restricted-properties` で `describe.skip` 等の禁止が不要になる。

* See
https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-disabled-tests.md
https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-focused-tests.md

## Tasks

- [x] Add linted file for `jest/no-disabled-tests` with keeping default
- [x] Add linted file for `jest/no-focused-tests` with keeping default
- [x] Remove unnecessary options from `no-restricted-properties`
- [x] Purge unnecessary linted file for `no-restricted-properties`
