### ISSUE TITLE
✅ Keep Jest rules

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#363]
## Overview

* Keep Jest rules

## Tasks

  - [ ] 🛠 Add intent rule file of `jest/expect-expect`
  - [ ] 🛠 Add intent rule file of `jest/max-expects`
  - [ ] 🛠 Add intent rule file of `jest/max-nested-describe`
  - [ ] 🛠 Add intent rule file of `jest/no-alias-methods`
  - [ ] 🛠 Add intent rule file of `jest/no-commented-out-tests`
  - [ ] 🛠 Add intent rule file of `jest/no-conditional-expect`
  - [ ] 🛠 Add intent rule file of `jest/no-conditional-in-test`
  - [ ] 🛠 Add intent rule file of `jest/no-deprecated-functions`
  - [ ] 🛠 Add intent rule file of `jest/no-disabled-tests`
  - [ ] 🛠 Add intent rule file of `jest/no-done-callback`
  - [ ] 🛠 Add intent rule file of `jest/no-duplicate-hooks`
  - [ ] 🛠 Add intent rule file of `jest/no-export`
  - [ ] 🛠 Add intent rule file of `jest/no-focused-tests`
  - [ ] 🛠 Add intent rule file of `jest/no-interpolation-in-snapshots`
  - [ ] 🛠 Add intent rule file of `jest/no-jasmine-globals`
  - [ ] 🛠 Add intent rule file of `jest/no-large-snapshots`
  - [ ] 🛠 Add intent rule file of `jest/no-mocks-import`
  - [ ] 🛠 Add intent rule file of `jest/no-restricted-jest-methods`
  - [ ] 🛠 Add intent rule file of `jest/no-restricted-matchers`
  - [x] #356
  - [ ] 🛠 Add intent rule file of `jest/no-test-prefixes`
  - [ ] 🛠 Add intent rule file of `jest/no-test-return-statement`
  - [ ] 🛠 Add intent rule file of `jest/no-untyped-mock-factory`
  - [ ] 🛠 Add intent rule file of `jest/prefer-called-with`
  - [ ] 🛠 Add intent rule file of `jest/prefer-comparison-matcher`
  - [ ] 🛠 Add intent rule file of `jest/prefer-each`
  - [ ] 🛠 Add intent rule file of `jest/prefer-equality-matcher`
  - [ ] 🛠 Add intent rule file of `jest/prefer-expect-resolves`
  - [ ] 🛠 Add intent rule file of `jest/prefer-hooks-in-order`
  - [ ] 🛠 Add intent rule file of `jest/prefer-hooks-on-top`
  - [ ] 🛠 Add intent rule file of `jest/prefer-mock-promise-shorthand`
  - [ ] 🛠 Add intent rule file of `jest/prefer-snapshot-hint`
  - [ ] 🛠 Add intent rule file of `jest/prefer-spy-on`
  - [ ] 🛠 Add intent rule file of `jest/prefer-strict-equal`
  - [ ] 🛠 Add intent rule file of `jest/prefer-to-be`
  - [ ] 🛠 Add intent rule file of `jest/prefer-to-contain`
  - [ ] 🛠 Add intent rule file of `jest/prefer-to-have-length`
  - [ ] 🛠 Add intent rule file of `jest/prefer-todo`
  - [ ] 🛠 Add intent rule file of `jest/require-to-throw-message`
  - [x] #358
  - [ ] ⚒ Add intent rule file of `jest/unbound-method`
  - [ ] 🛠 Add intent rule file of `jest/valid-describe-callback`
  - [ ] 🛠 Add intent rule file of `jest/valid-expect-in-promise`
  - [ ] 🛠 Add intent rule file of `jest/valid-expect`
