### ISSUE TITLE
🐛 Clean up exempted files for npm run lint

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#365]
## Overview

* Clean up exempted files for npm run lint

## Tasks

- [x] `for-direction`
- [x] `function-call-argument-newline`
- [x] `guard-for-in`
- [x] `jest/no-identical-title`
- [x] `line-comment-position`
- [x] `no-continue`
- [x] `no-inline-comments`
- [x] `prefer-named-capture-group`
- [x] `sort-vars`
