### ISSUE TITLE
⚙️ Setup `jsdoc/xxxx` with default options

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#370]
## Overview

* Setup `jsdoc/xxxx` with default options

* Use (#38)

```
npx eslint --print-config > rules.txt
```

## Tasks
  - [x] `check-access`
  - [x] `check-alignment`
  - [x] ~`check-examples`~
  - [x] `check-indentation`
  - [x] `check-line-alignment`
  - [x] `check-param-names`
  - [x] `check-property-names`
  - [x] `check-syntax`
  - [x] `check-tag-names`
  - [x] `check-types`
  - [x] `check-values`
  - [x] `empty-tags`
  - [x] `implements-on-classes`
  - [x] `imports-as-dependencies`
  - [x] `informative-docs`
  - [x] `match-description`
  - [x] `match-name`
  - [x] `multiline-blocks`
  - [x] `no-bad-blocks`
  - [x] `no-blank-block-descriptions`
  - [x] `no-blank-blocks`
  - [x] `no-defaults`
  - [x] `no-missing-syntax`
  - [x] `no-multi-asterisks`
  - [x] `no-restricted-syntax`
  - [x] `no-types`
  - [x] `no-undefined-types`
  - [x] `require-asterisk-prefix`
  - [x] `require-description`
  - [x] `require-description-complete-sentence`
  - [x] `require-example`
  - [x] `require-file-overview`
  - [x] `require-hyphen-before-param-description`
  - [x] `require-jsdoc`
  - [x] `require-param`
  - [x] `require-param-description`
  - [x] `require-param-name`
  - [x] `require-param-type`
  - [x] `require-property`
  - [x] `require-property-description`
  - [x] `require-property-name`
  - [x] `require-property-type`
  - [x] `require-returns`
  - [x] `require-returns-check`
  - [x] `require-returns-description`
  - [x] `require-returns-type`
  - [x] `require-throws`
  - [x] `require-yields`
  - [x] `require-yields-check`
  - [x] `sort-tags`
  - [x] `tag-lines`
  - [x] `text-escaping`
  - [x] `valid-types`
