### ISSUE TITLE
🐛 Remove `contexts: []` from all options

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#379]
## Overview

* Remove `contexts: []` from all options

* It is stop to work some rules (ex: `jsdoc/require-description`)

## Tasks

* Keep it
    - [x] ~`exemptTagContexts` of `jsdoc/check-types`~
    - [x] `context` of `jsdoc/no-missing-syntax`
    - [x] `context` of `jsdoc/no-restricted-syntax`
    - [x] `context` of `jsdoc/no-types`
    - [x] `context` of `jsdoc/require-jsdoc`

* Remove it
    - [x] `context` of `jsdoc/implements-on-classes`
    - [x] `context` of `jsdoc/no-defaults`
    - [x] `context` of `jsdoc/require-example`
    - [x] `context` of `jsdoc/require-param-name`
    - [x] `context` of `jsdoc/require-returns`
    - [x] `context` of `jsdoc/require-returns-description`
    - [x] `context` of `jsdoc/require-returns-type`
    - [x] `context` of `jsdoc/require-throws`
    - [x] `context` of `jsdoc/require-yields`
