### ISSUE TITLE
✅ Keep JSDoc rules

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#408]
## Overview

* Keep JSDoc rules

## Tasks

* Fixed keeping rules
  - [ ] ⚙️ Add linted files for `jsdoc/check-access`
  - [x] #366
  - [x] #390
  - [x] #398

* All rules
  - [ ] ⚙️ Add linted files for `jsdoc/check-line-alignment`
  - [ ] ⚙️ Add linted files for `jsdoc/check-param-names`
  - [ ] ⚙️ Add linted files for `jsdoc/check-property-names`
  - [ ] ⚙️ Add linted files for `jsdoc/check-syntax`
  - [ ] ⚙️ Add linted files for `jsdoc/check-tag-names`
  - [ ] ⚙️ Add linted files for `jsdoc/check-values`
  - [ ] ⚙️ Add linted files for `jsdoc/empty-tags`
  - [ ] ⚙️ Add linted files for `jsdoc/implements-on-classes`
  - [ ] ⚙️ Add linted files for `jsdoc/imports-as-dependencies`
  - [ ] ⚙️ Add linted files for `jsdoc/match-name`
  - [ ] ⚙️ Add linted files for `jsdoc/no-bad-blocks`
  - [ ] ⚙️ Add linted files for `jsdoc/no-blank-block-descriptions`
  - [ ] ⚙️ Add linted files for `jsdoc/no-blank-blocks`
  - [ ] ⚙️ Add linted files for `jsdoc/no-defaults`
  - [ ] ⚙️ Add linted files for `jsdoc/no-missing-syntax`
  - [ ] ⚙️ Add linted files for `jsdoc/no-restricted-syntax`
  - [ ] ⚙️ Add linted files for `jsdoc/no-types`
  - [ ] ⚙️ Add linted files for `jsdoc/no-undefined-types`
  - [ ] ⚙️ Add linted files for `jsdoc/require-asterisk-prefix`
  - [ ] ⚙️ Add linted files for `jsdoc/require-hyphen-before-param-description`
  - [ ] ⚙️ Add linted files for `jsdoc/require-param-description`
  - [ ] ⚙️ Add linted files for `jsdoc/require-param-name`
  - [ ] ⚙️ Add linted files for `jsdoc/require-param-type`
  - [ ] ⚙️ Add linted files for `jsdoc/require-param`
  - [ ] ⚙️ Add linted files for `jsdoc/require-property-description`
  - [ ] ⚙️ Add linted files for `jsdoc/require-property-name`
  - [ ] ⚙️ Add linted files for `jsdoc/require-property-type`
  - [ ] ⚙️ Add linted files for `jsdoc/require-property`
  - [ ] ⚙️ Add linted files for `jsdoc/require-returns-check`
  - [ ] ⚙️ Add linted files for `jsdoc/require-returns-description`
  - [ ] ⚙️ Add linted files for `jsdoc/require-returns-type`
  - [ ] ⚙️ Add linted files for `jsdoc/require-returns`
  - [ ] ⚙️ Add linted files for `jsdoc/require-throws`
  - [ ] ⚙️ Add linted files for `jsdoc/require-yields-check`
  - [ ] ⚙️ Add linted files for `jsdoc/require-yields`
  - [ ] ⚙️ Add linted files for `jsdoc/valid-types`

* Suspended
  - [ ] ⚙️ Add linted files for `jsdoc/check-examples` (have not yet added)
    > NOTE: This rule currently does not work in ESLint 8
    > (we are waiting for https://github.com/eslint/eslint/issues/14745).
