### ISSUE TITLE
🧹 Purge `// @ts-expect-error` if possible

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#411]
## Overview

* Purge `// @ts-expect-error` if possible

## Tasks

- [ ] `linted/default/no-global-assign`
- [ ] `linted/default/no-undef`
- [ ] `linted/default/no-empty-function`
- [ ] `linted/default/no-use-before-define`
- [ ] `linted/default/use-isnan`
