### ISSUE TITLE
🚀 Publish `1.0.0`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#420]
## Overview

* Publish version as `1.0.0`.

## Tasks

- [x] #421
- [x] Publish.
- [x] Merge to `main` as `1.0.0`.

## npm login before publishing

* npm login to GitHub Packages

    - [x] get login password from your GitHub settings
Go to → https://github.com/settings/tokens
    - [x] copy your `personal access token` created
    - [x] run in terminal
        ```
        % npm login --registry=https://npm.pkg.github.com/

        Username: your-github-account-in-lower-case-only
        Password:
        Email: your.mail.account@gmail.com
        Logged in as [your-name] on https://npm.pkg.github.com/.
        ```

## Procedure to Publish

1. Check Commit Hash to Publish

    - [x] git log --graph --oneline --decorate --all
    - [x] target commit as: `871fcd9`

2. Confirm Work to Publish

    - [x] package.json
    - [x] package-lock.json

3. Publish

    - [x] `npm publish --dry-run`

        ```
        % npm publish --dry-run
        npm notice 
        npm notice 📦  @steweucen/eslint-config@1.0.0
        npm notice === Tarball Contents === 
        npm notice 28.2kB .eslintrc.default.yml                                              
        npm notice 31.3kB .eslintrc.yml                                                      
        npm notice 697B   .github/workflows/test.yml                                         
        npm notice 608B   .vscode/cspell.json                                                
        npm notice 90B    jest.config.js                                                     
        npm notice 871B   package.json                                                       
        npm notice 79B    playground/sample.js                                               
        npm notice 12.6kB rules.txt                                                          
        npm notice 957B   tests/__tests__/verify-eslint-config.js                            
        npm notice 454B   tests/exempted/array-bracket-newline.js                            
        npm notice 478B   tests/exempted/array-element-newline.js                            
        npm notice 560B   tests/exempted/capitalized-comments.js                             
        npm notice 300B   tests/exempted/dot-notation.js                                     
        npm notice 330B   tests/exempted/for-direction.js                                    
        npm notice 415B   tests/exempted/func-names.js                                       
        npm notice 407B   tests/exempted/func-style.js                                       
        npm notice 547B   tests/exempted/function-call-argument-newline.js                   
        npm notice 347B   tests/exempted/function-paren-newline.js                           
        npm notice 263B   tests/exempted/guard-for-in.js                                     
        npm notice 257B   tests/exempted/implicit-arrow-linebreak.js                         
        npm notice 846B   tests/exempted/jest/no-hooks.js                                    
        npm notice 259B   tests/exempted/jest/no-identical-title.js                          
        npm notice 202B   tests/exempted/jest/prefer-expect-assertions.js                    
        npm notice 1.5kB  tests/exempted/jsdoc/require-description-complete-sentence.js      
        npm notice 613B   tests/exempted/jsdoc/require-description.js                        
        npm notice 425B   tests/exempted/jsdoc/require-example.js                            
        npm notice 512B   tests/exempted/jsdoc/text-escaping.js                              
        npm notice 216B   tests/exempted/line-comment-position.js                            
        npm notice 125B   tests/exempted/max-len.js                                          
        npm notice 916B   tests/exempted/max-lines-per-function.js                           
        npm notice 3.4kB  tests/exempted/max-lines.js                                        
        npm notice 874B   tests/exempted/max-params.js                                       
        npm notice 451B   tests/exempted/max-statements.js                                   
        npm notice 309B   tests/exempted/multiline-comment-style.js                          
        npm notice 858B   tests/exempted/no-bitwise.js                                       
        npm notice 245B   tests/exempted/no-continue.js                                      
        npm notice 164B   tests/exempted/no-extra-parens.js                                  
        npm notice 203B   tests/exempted/no-inline-comments.js                               
        npm notice 353B   tests/exempted/no-lone-blocks.js                                   
        npm notice 605B   tests/exempted/no-magic-numbers.js                                 
        npm notice 199B   tests/exempted/no-ternary.js                                       
        npm notice 655B   tests/exempted/no-undefined.js                                     
        npm notice 1.1kB  tests/exempted/no-underscore-dangle.js                             
        npm notice 395B   tests/exempted/object-property-newline.js                          
        npm notice 356B   tests/exempted/prefer-named-capture-group.js                       
        npm notice 133B   tests/exempted/sort-keys.js                                        
        npm notice 189B   tests/exempted/sort-vars.js                                        
        npm notice 183B   tests/exempted/wrap-regex.js                                       
        npm notice 443B   tests/linted/default/accessor-pairs.js                             
        npm notice 1.4kB  tests/linted/default/array-bracket-spacing.js                      
        npm notice 314B   tests/linted/default/arrow-body-style.js                           
        npm notice 797B   tests/linted/default/arrow-spacing.js                              
        npm notice 3.1kB  tests/linted/default/brace-style.js                                
        npm notice 346B   tests/linted/default/class-methods-use-this.js                     
        npm notice 55B    tests/linted/default/eol-last.js                                   
        npm notice 1.7kB  tests/linted/default/jest/no-disabled-tests.js                     
        npm notice 1.4kB  tests/linted/default/jest/no-focused-tests.js                      
        npm notice 254B   tests/linted/default/jest/no-standalone-expect.js                  
        npm notice 1.4kB  tests/linted/default/jest/require-hook.js                          
        npm notice 304B   tests/linted/default/jest/require-top-level-describe.js            
        npm notice 664B   tests/linted/default/jsdoc/check-alignment.js                      
        npm notice 1.5kB  tests/linted/default/jsdoc/check-types.js                          
        npm notice 401B   tests/linted/default/jsdoc/informative-docs.js                     
        npm notice 763B   tests/linted/default/jsdoc/multiline-blocks.js                     
        npm notice 1.2kB  tests/linted/default/no-confusing-arrow.js                         
        npm notice 581B   tests/linted/default/no-control-regex.js                           
        npm notice 460B   tests/linted/default/no-empty.js                                   
        npm notice 220B   tests/linted/default/no-global-assign.js                           
        npm notice 290B   tests/linted/default/no-mixed-operators.js                         
        npm notice 300B   tests/linted/default/no-undef.js                                   
        npm notice 1.8kB  tests/linted/default/object-curly-newline.js                       
        npm notice 447B   tests/linted/default/prefer-destructuring.js                       
        npm notice 422B   tests/linted/default/prefer-numeric-literals.js                    
        npm notice 258B   tests/linted/default/prefer-template.js                            
        npm notice 1.3kB  tests/linted/default/space-before-blocks.js                        
        npm notice 777B   tests/linted/default/space-before-function-paren.js                
        npm notice 151B   tests/linted/initials/indent.js                                    
        npm notice 66B    tests/linted/initials/quotes.js                                    
        npm notice 292B   tests/linted/initials/semi.js                                      
        npm notice 454B   tests/linted/standard/array-bracket-newline.js                     
        npm notice 1.7kB  tests/linted/standard/array-callback-return.js                     
        npm notice 355B   tests/linted/standard/array-element-newline.js                     
        npm notice 701B   tests/linted/standard/arrow-parens.js                              
        npm notice 850B   tests/linted/standard/comma-dangle.js                              
        npm notice 1.0kB  tests/linted/standard/complexity.js                                
        npm notice 685B   tests/linted/standard/consistent-return.js                         
        npm notice 274B   tests/linted/standard/dot-location.js                              
        npm notice 421B   tests/linted/standard/func-names.js                                
        npm notice 422B   tests/linted/standard/function-call-argument-newline.js            
        npm notice 347B   tests/linted/standard/function-paren-newline.js                    
        npm notice 570B   tests/linted/standard/generator-star-spacing.js                    
        npm notice 796B   tests/linted/standard/grouped-accessor-pairs.js                    
        npm notice 1.1kB  tests/linted/standard/id-denylist.js                               
        npm notice 1.1kB  tests/linted/standard/id-match.js                                  
        npm notice 354B   tests/linted/standard/jest/consistent-test-it.js                   
        npm notice 544B   tests/linted/standard/jest/prefer-lowercase-title.js               
        npm notice 1.3kB  tests/linted/standard/jest/valid-title.js                          
        npm notice 1.5kB  tests/linted/standard/jsdoc/check-indentation.js                   
        npm notice 1.0kB  tests/linted/standard/jsdoc/match-description.js                   
        npm notice 992B   tests/linted/standard/jsdoc/no-multi-asterisks.js                  
        npm notice 729B   tests/linted/standard/jsdoc/require-jsdoc.js                       
        npm notice 2.1kB  tests/linted/standard/jsdoc/sort-tags.js                           
        npm notice 822B   tests/linted/standard/jsdoc/tag-lines.js                           
        npm notice 737B   tests/linted/standard/lines-around-comment.js                      
        npm notice 300B   tests/linted/standard/max-classes-per-file.js                      
        npm notice 719B   tests/linted/standard/max-params.js                                
        npm notice 311B   tests/linted/standard/newline-per-chained-call.js                  
        npm notice 1.5kB  tests/linted/standard/no-empty-function.js                         
        npm notice 1.7kB  tests/linted/standard/no-extra-boolean-cast.js                     
        npm notice 1.0kB  tests/linted/standard/no-implicit-coercion.js                      
        npm notice 6.2kB  tests/linted/standard/no-irregular-whitespace.js                   
        npm notice 406B   tests/linted/standard/no-multiple-empty-lines.js                   
        npm notice 1.1kB  tests/linted/standard/no-param-reassign.js                         
        npm notice 320B   tests/linted/standard/no-restricted-syntax/noDoWhile.js            
        npm notice 394B   tests/linted/standard/no-restricted-syntax/noFor.js                
        npm notice 311B   tests/linted/standard/no-restricted-syntax/noForEach.js            
        npm notice 328B   tests/linted/standard/no-restricted-syntax/noForIn.js              
        npm notice 315B   tests/linted/standard/no-restricted-syntax/noForOf.js              
        npm notice 3.3kB  tests/linted/standard/no-restricted-syntax/noIfInHigherOrderFunc.js
        npm notice 276B   tests/linted/standard/no-restricted-syntax/noLet.js                
        npm notice 981B   tests/linted/standard/no-restricted-syntax/noNestedIf.js           
        npm notice 864B   tests/linted/standard/no-restricted-syntax/noSuffix.js             
        npm notice 322B   tests/linted/standard/no-restricted-syntax/noSwitch.js             
        npm notice 406B   tests/linted/standard/no-restricted-syntax/noWhile.js              
        npm notice 1.3kB  tests/linted/standard/no-shadow.js                                 
        npm notice 605B   tests/linted/standard/no-unneeded-ternary.js                       
        npm notice 4.5kB  tests/linted/standard/no-unsafe-optional-chaining.js               
        npm notice 508B   tests/linted/standard/no-unused-vars.js                            
        npm notice 1.5kB  tests/linted/standard/no-use-before-define.js                      
        npm notice 1.3kB  tests/linted/standard/object-curly-spacing.js                      
        npm notice 462B   tests/linted/standard/object-property-newline.js                   
        npm notice 1.3kB  tests/linted/standard/object-shorthand.js                          
        npm notice 128B   tests/linted/standard/one-var.js                                   
        npm notice 3.8kB  tests/linted/standard/operator-linebreak.js                        
        npm notice 855B   tests/linted/standard/padded-blocks.js                             
        npm notice 1.5kB  tests/linted/standard/padding-line-between-statements.js           
        npm notice 214B   tests/linted/standard/quote-props.js                               
        npm notice 506B   tests/linted/standard/radix.js                                     
        npm notice 700B   tests/linted/standard/semi-style.js                                
        npm notice 708B   tests/linted/standard/spaced-comment.js                            
        npm notice 401B   tests/linted/standard/template-tag-spacing.js                      
        npm notice 1.2kB  tests/linted/standard/use-isnan.js                                 
        npm notice 619B   tests/linted/standard/wrap-iife.js                                 
        npm notice 422B   tests/linted/standard/yield-star-spacing.js                        
        npm notice === Tarball Details === 
        npm notice name:          @steweucen/eslint-config                
        npm notice version:       1.0.0                                   
        npm notice filename:      @steweucen/eslint-config-1.0.0.tgz      
        npm notice package size:  35.3 kB                                 
        npm notice unpacked size: 183.8 kB                                
        npm notice shasum:        76c24b38e913d30b4602e46702a4074d87f46fe1
        npm notice integrity:     sha512-Xdky7eVAvtDjF[...]BfDJ3IJYt1HJg==
        npm notice total files:   144                                     
        npm notice 
        npm notice Publishing to https://npm.pkg.github.com (dry-run)
        + @steweucen/eslint-config@1.0.0
        ```

    - [x] Check log of `--dry-run` by other member before actual publishing.
    - [x] `npm publish`
