### ISSUE TITLE
⚙️ Fulfill default params and options for all rules

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#43]
## Overview

* Fulfill default params and options for all rules

## Tasks

  - [x] `accessor-pairs`
  - [x] `array-bracket-newline`
  - [x] `array-bracket-spacing`
  - [x] `array-callback-return`
  - [x] `array-element-newline`
  - [x] `arrow-body-style`
  - [x] `arrow-parens`
  - [x] `arrow-spacing`
  - [x] `block-scoped-var`
  - [x] `block-spacing`
  - [x] `brace-style`
  - [x] `camelcase`
  - [x] `capitalized-comments`
  - [x] `class-methods-use-this`
  - [x] `comma-dangle`
  - [x] `comma-spacing`
  - [x] `comma-style`
  - [x] `complexity`
  - [x] `computed-property-spacing`
  - [x] `consistent-return`
  - [x] `consistent-this`
  - [x] `constructor-super`
  - [x] `curly`
  - [x] `default-case`
  - [x] `default-case-last`
  - [x] `default-param-last`
  - [x] `dot-location`
  - [x] `dot-notation`
  - [x] `eol-last`
  - [x] `eqeqeq`
  - [x] `for-direction`
  - [x] `func-call-spacing`
  - [x] `func-name-matching`
  - [x] `func-names`
  - [x] `func-style`
  - [x] `function-call-argument-newline`
  - [x] `function-paren-newline`
  - [x] `generator-star-spacing`
  - [x] `getter-return`
  - [x] `grouped-accessor-pairs`
  - [x] `guard-for-in`
  - [x] `id-denylist`
  - [x] `id-length`
  - [x] `id-match`
  - [x] `implicit-arrow-linebreak`
  - [x] `init-declarations`
  - [x] `jsx-quotes`
  - [x] `key-spacing`
  - [x] `keyword-spacing`
  - [x] `line-comment-position`
  - [x] `linebreak-style`
  - [x] `lines-around-comment`
  - [x] `lines-between-class-members`
  - [x] `logical-assignment-operators`
  - [x] `max-classes-per-file`
  - [x] `max-depth`
  - [x] `max-len`
  - [x] `max-lines`
  - [x] `max-lines-per-function`
  - [x] `max-nested-callbacks`
  - [x] `max-params`
  - [x] `max-statements`
  - [x] `max-statements-per-line`
  - [x] `multiline-comment-style`
  - [x] `multiline-ternary`
  - [x] `new-cap`
  - [x] `new-parens`
  - [x] `newline-per-chained-call`
  - [x] `no-alert`
  - [x] `no-array-constructor`
  - [x] `no-async-promise-executor`
  - [x] `no-await-in-loop`
  - [x] `no-bitwise`
  - [x] `no-caller`
  - [x] `no-case-declarations`
  - [x] `no-class-assign`
  - [x] `no-compare-neg-zero`
  - [x] `no-cond-assign`
  - [x] `no-confusing-arrow`
  - [x] `no-console`
  - [x] `no-const-assign`
  - [x] `no-constant-binary-expression`
  - [x] `no-constant-condition`
  - [x] `no-constructor-return`
  - [x] `no-continue`
  - [x] `no-control-regex`
  - [x] `no-debugger`
  - [x] `no-delete-var`
  - [x] `no-div-regex`
  - [x] `no-dupe-args`
  - [x] `no-dupe-class-members`
  - [x] `no-dupe-else-if`
  - [x] `no-dupe-keys`
  - [x] `no-duplicate-case`
  - [x] `no-duplicate-imports`
  - [x] `no-else-return`
  - [x] `no-empty`
  - [x] `no-empty-character-class`
  - [x] `no-empty-function`
  - [x] `no-empty-pattern`
  - [x] `no-eq-null`
  - [x] `no-eval`
  - [x] `no-ex-assign`
  - [x] `no-extend-native`
  - [x] `no-extra-bind`
  - [x] `no-extra-boolean-cast`
  - [x] `no-extra-label`
  - [x] `no-extra-parens`
  - [x] `no-extra-semi`
  - [x] `no-fallthrough`
  - [x] `no-floating-decimal`
  - [x] `no-func-assign`
  - [x] `no-global-assign`
  - [x] `no-implicit-coercion`
  - [x] `no-implicit-globals`
  - [x] `no-implied-eval`
  - [x] `no-import-assign`
  - [x] `no-inline-comments`
  - [x] `no-inner-declarations`
  - [x] `no-invalid-regexp`
  - [x] `no-invalid-this`
  - [x] `no-irregular-whitespace`
  - [x] `no-iterator`
  - [x] `no-label-var`
  - [x] `no-labels`
  - [x] `no-lone-blocks`
  - [x] `no-lonely-if`
  - [x] `no-loop-func`
  - [x] `no-loss-of-precision`
  - [x] `no-magic-numbers`
  - [x] `no-misleading-character-class`
  - [x] `no-mixed-operators`
  - [x] `no-mixed-spaces-and-tabs`
  - [x] `no-multi-assign`
  - [x] `no-multi-spaces`
  - [x] `no-multi-str`
  - [x] `no-multiple-empty-lines`
  - [x] `no-negated-condition`
  - [x] `no-nested-ternary`
  - [x] `no-new`
  - [x] `no-new-func`
  - [x] `no-new-object`
  - [x] `no-new-symbol`
  - [x] `no-new-wrappers`
  - [x] `no-nonoctal-decimal-escape`
  - [x] `no-obj-calls`
  - [x] `no-octal`
  - [x] `no-octal-escape`
  - [x] `no-param-reassign`
  - [x] `no-plusplus`
  - [x] `no-promise-executor-return`
  - [x] `no-proto`
  - [x] `no-prototype-builtins`
  - [x] `no-redeclare`
  - [x] `no-regex-spaces`
  - [x] `no-restricted-exports`
  - [x] `no-restricted-globals`
  - [x] `no-restricted-imports`
  - [x] `no-restricted-properties`
  - [x] `no-restricted-syntax`
  - [x] `no-return-assign`
  - [x] `no-return-await`
  - [x] `no-script-url`
  - [x] `no-self-assign`
  - [x] `no-self-compare`
  - [x] `no-sequences`
  - [x] `no-setter-return`
  - [x] `no-shadow`
  - [x] `no-shadow-restricted-names`
  - [x] `no-sparse-arrays`
  - [x] `no-tabs`
  - [x] `no-template-curly-in-string`
  - [x] `no-ternary`
  - [x] `no-this-before-super`
  - [x] `no-throw-literal`
  - [x] `no-trailing-spaces`
  - [x] `no-undef`
  - [x] `no-undef-init`
  - [x] `no-undefined`
  - [x] `no-underscore-dangle`
  - [x] `no-unexpected-multiline`
  - [x] `no-unmodified-loop-condition`
  - [x] `no-unneeded-ternary`
  - [x] `no-unreachable`
  - [x] `no-unreachable-loop`
  - [x] `no-unsafe-finally`
  - [x] `no-unsafe-negation`
  - [x] `no-unsafe-optional-chaining`
  - [x] `no-unused-expressions`
  - [x] `no-unused-labels`
  - [x] `no-unused-private-class-members`
  - [x] `no-unused-vars`
  - [x] `no-use-before-define`
  - [x] `no-useless-backreference`
  - [x] `no-useless-call`
  - [x] `no-useless-catch`
  - [x] `no-useless-computed-key`
  - [x] `no-useless-concat`
  - [x] `no-useless-constructor`
  - [x] `no-useless-escape`
  - [x] `no-useless-rename`
  - [x] `no-useless-return`
  - [x] `no-var`
  - [x] `no-void`
  - [x] `no-warning-comments`
  - [x] `no-whitespace-before-property`
  - [x] `no-with`
  - [x] `nonblock-statement-body-position`
  - [x] `object-curly-newline`
  - [x] `object-curly-spacing`
  - [x] `object-property-newline`
  - [x] `object-shorthand`
  - [x] `one-var`
  - [x] `one-var-declaration-per-line`
  - [x] `operator-assignment`
  - [x] `operator-linebreak`
  - [x] `padded-blocks`
  - [x] `padding-line-between-statements`
  - [x] `prefer-arrow-callback`
  - [x] `prefer-const`
  - [x] `prefer-destructuring`
  - [x] `prefer-exponentiation-operator`
  - [x] `prefer-named-capture-group`
  - [x] `prefer-numeric-literals`
  - [x] `prefer-object-has-own`
  - [x] `prefer-object-spread`
  - [x] `prefer-promise-reject-errors`
  - [x] `prefer-regex-literals`
  - [x] `prefer-rest-params`
  - [x] `prefer-spread`
  - [x] `prefer-template`
  - [x] `quote-props`
  - [x] `radix`
  - [x] `require-atomic-updates`
  - [x] `require-await`
  - [x] `require-unicode-regexp`
  - [x] `require-yield`
  - [x] `rest-spread-spacing`
  - [x] `semi-spacing`
  - [x] `semi-style`
  - [x] `sort-imports`
  - [x] `sort-keys`
  - [x] `sort-vars`
  - [x] `space-before-blocks`
  - [x] `space-before-function-paren`
  - [x] `space-in-parens`
  - [x] `space-infix-ops`
  - [x] `space-unary-ops`
  - [x] `spaced-comment`
  - [x] `strict`
  - [x] `switch-colon-spacing`
  - [x] `symbol-description`
  - [x] `template-curly-spacing`
  - [x] `template-tag-spacing`
  - [x] `unicode-bom`
  - [x] `use-isnan`
  - [x] `valid-typeof`
  - [x] `vars-on-top`
  - [x] `wrap-iife`
  - [x] `wrap-regex`
  - [x] `yield-star-spacing`
  - [x] `yoda`
