### ISSUE TITLE
🚀 Publish `1.0.1`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#444]
## Overview

* Publish version as `1.0.1`.

## Tasks

- [x] #445
- [x] Publish.
- [x] Merge to `main` as `1.0.1`.

## npm login before publishing

* npm login to GitHub Packages

    - get login password from your GitHub settings
Go to → https://github.com/settings/tokens
    - copy your `personal access token` created
    - run in terminal
        ```
        % npm login --registry=https://npm.pkg.github.com/

        Username: your-github-account-in-lower-case-only
        Password:
        Email: your.mail.account@gmail.com
        Logged in as [your-name] on https://npm.pkg.github.com/.
        ```

## Procedure to Publish

1. Check Commit Hash to Publish

    - [x] git log --graph --oneline --decorate --all
    - [x] target commit as: `537d744`

2. Confirm Work to Publish

    - [x] package.json
    - [x] package-lock.json

3. Publish

    - [x] `npm publish --dry-run`

        ```
        % npm publish --dry-run
        npm notice 
        npm notice 📦  @steweucen/eslint-config@1.0.1
        npm notice === Tarball Contents === 
        npm notice 31.3kB .eslintrc.yml
        npm notice 1.1kB  LICENSE      
        npm notice 722B   README.md    
        npm notice 940B   package.json 
        npm notice === Tarball Details === 
        npm notice name:          @steweucen/eslint-config                
        npm notice version:       1.0.1                                   
        npm notice filename:      @steweucen/eslint-config-1.0.1.tgz      
        npm notice package size:  9.3 kB                                  
        npm notice unpacked size: 34.0 kB                                 
        npm notice shasum:        b4915cbadec7dcf285e61d04241e04bff5032303
        npm notice integrity:     sha512-pHZ+Rubk49x/I[...]8PJAZvHLtAcsA==
        npm notice total files:   4                                       
        npm notice 
        npm notice Publishing to https://npm.pkg.github.com (dry-run)
        + @steweucen/eslint-config@1.0.1
        ```

    - [x] Check log of `--dry-run` by other member before actual publishing.
    - [x] `npm publish`
