### ISSUE TITLE
🐛 Fix `dependencies` into `package.json`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#451]
## Overview

* Fix `dependencies` into `package.json`

## Tasks

- [x] Replace `eslint-plugin-jest` to `dependencies` of `package.json`
- [x] Replace `eslint-plugin-jsdoc` to `dependencies` of `package.json`
- [x] Update `package-lock.json` by npm install
