### ISSUE TITLE
🚀 Publish `1.3.0`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#525]
## Overview

* Publish version as `1.3.0`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #526
- [x] Publish by procedure
- [x] #528
- [x] Push version tag `1.3.0` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `612112a`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice
  npm notice 📦  @steweucen/eslint-config@1.3.0
  npm notice Tarball Contents
  npm notice 31.6kB .eslintrc.yml
  npm notice 1.1kB LICENSE
  npm notice 681B README.md
  npm notice 1.0kB package.json
  npm notice Tarball Details
  npm notice name: @steweucen/eslint-config
  npm notice version: 1.3.0
  npm notice filename: steweucen-eslint-config-1.3.0.tgz
  npm notice package size: 9.4 kB
  npm notice unpacked size: 34.4 kB
  npm notice shasum: 348317d8467d552654d27bc99445b298ebed9fb7
  npm notice integrity: sha512-xqkprDZSfAzoK[...]ukxgFA11NyL0A==
  npm notice total files: 4
  npm notice
  npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
  + @steweucen/eslint-config@1.3.0
  ```

- [x] ~Check log of `--dry-run` by other member before actual publishing~
  - target commit as: `612112a`
  - node version: `v20.14.0`
  - npm version: `10.7.0`

- [x] Publish

  ```console
  git status
  git diff 612112a
  ```

  ```console
  npm publish
  ```
