### ISSUE TITLE
💪 Resolve `@stylistic` rules

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#546]
## Overview

* Resolve `@stylistic` rules

## Tasks

- [x] Replace linted files of `stylistic` rules to the `@stylistic/` directory
- [x] Add '@stylistc/' plugin prefix in eslint annotation comment
- [x] Add eslint annotation comment for `@stylistic/indent-binary-ops`
- [x] Add linted file for `@stylistic/indent-binary-ops`
