### ISSUE TITLE
⚙️ Restore test with `ESLintInspector` to resume test in GitHub Workflows

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#548]
## Overview

* Restore test with `ESLintInspector` to resume test in GitHub Workflows

## Tasks

- [x] Turn on some rules required for us
- [x] Turn on and adjust some rules
- [x] Adjust options of `jsdoc/require-jsdoc` for us
- [x] Remove eslint annotation that makes warning in linted files
- [x] Resolve `no-undiff` error in `linted/default$/jsdoc/multiline-blocks.js`
- [x] Update linted file to fix `fdescribe()` and `fix()`
