### ISSUE TITLE
💪 Resolve linted file of `no-undefined`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#557]
## Overview

* Resolve linted file of `no-undefined`

## Tasks

- [x] Replace exempted `no-undefined` file to `linted/default$/`
- [x] Update `tests/linted/default$/no-undefined.js` to change comment at linted points
- [x] Comment out some options that has `undefined` value in configuration files
