### ISSUE TITLE
💪 Restore exempted files to resume GitHub Workflows

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#560]
## Overview

* Restore exempted files to resume GitHub Workflows

## Tasks

- [x] Fix `no-unused` error in `exempted$/jsdoc/multiline-blocks.js`
- [x] Add `@stylistic` plugin prefix in exempted lint file
- [x] Adjust options of `no-restricted-syntax` concerning `getItem` and `setItem`
