### ISSUE TITLE
🚀 Publish `2.0.0`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#578]
## Overview

* Publish version as `2.0.0`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #579
- [x] Publish by procedure
- [x] #583
- [x] Push version tag `2.0.0` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `89acc00`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice
  npm notice 📦  @steweucen/eslint-config@2.0.0
  npm notice Tarball Contents
  npm notice 1.1kB LICENSE
  npm notice 3.7kB README.md
  npm notice 1.7kB eslint.config.js
  npm notice 128B eslint.config.mjs
  npm notice 1.4kB package.json
  npm notice Tarball Details
  npm notice name: @steweucen/eslint-config
  npm notice version: 2.0.0
  npm notice filename: steweucen-eslint-config-2.0.0.tgz
  npm notice package size: 2.6 kB
  npm notice unpacked size: 7.9 kB
  npm notice shasum: b6f2cf4f202aa0cf6850d13a9329ff0cd82beedc
  npm notice integrity: sha512-fPM9C3sIUKqoq[...]fOb0VW460ezUQ==
  npm notice total files: 5
  npm notice
  npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
  + @steweucen/eslint-config@2.0.0
  ```

- [x] ~Check log of `--dry-run` by other member before actual publishing~
  - target commit as: `89acc00`
  - node version: `v20.14.0`
  - npm version: `10.7.0`

- [x] Publish

  ```console
  git status
  git diff 89acc00 @
  ```

  ```console
  npm publish
  ```
