### ISSUE TITLE
🚀 Publish `2.0.1`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#589]
## Overview

* Publish version as `2.0.1`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #590
- [x] Publish by procedure
- [x] #592
- [x] Push version tag `2.0.1` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `1f1ed25`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice
  npm notice 📦  @steweucen/eslint-config@2.0.1
  npm notice Tarball Contents
  npm notice 1.1kB LICENSE
  npm notice 3.7kB README.md
  npm notice 9.5kB configurations/core.js
  npm notice 1.2kB configurations/plugins/jest.js
  npm notice 8.8kB configurations/plugins/jsdoc.js
  npm notice 516B configurations/plugins/openreachtech.js
  npm notice 6.8kB configurations/plugins/stylistic.js
  npm notice 1.7kB eslint.config.js
  npm notice 128B eslint.config.mjs
  npm notice 1.4kB package.json
  npm notice Tarball Details
  npm notice name: @steweucen/eslint-config
  npm notice version: 2.0.1
  npm notice filename: steweucen-eslint-config-2.0.1.tgz
  npm notice package size: 8.6 kB
  npm notice unpacked size: 34.7 kB
  npm notice shasum: 9b5b5797d39b40688a5eb5c464b87c93beb7505e
  npm notice integrity: sha512-/VELFLo7BvLLw[...]f4YpOM5Ze6AzA==
  npm notice total files: 10
  npm notice
  npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
  + @steweucen/eslint-config@2.0.1
  ```

- [x] ~Check log of `--dry-run` by other member before actual publishing~
  - target commit as: `1f1ed25`
  - node version: `v20.14.0`
  - npm version: `10.7.0`

- [x] Publish

  ```console
  git status
  git diff 1f1ed25
  ```

  ```console
  npm publish --access public
  ```

**Comment by StewEucen** [comment]
* Publish `2.0.1`

https://github.com/StewEucen/eslint-config/pkgs/npm/eslint-config/226785888
