### ISSUE TITLE
🧹 Wipe out all lints in existing files

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#72]
## Overview

* Wipe out all lints in existing files

## Target Files

* `jest.config.js`
  - add trailing comma in two lines
* `tests/__tests__/sample.js`
  - remove the file
* `tests/__tests__/verify-eslint-config.js`
  - wrap `test()` by top level `discribe()`

## Tasks

- [x] `jest.config.js`
- [x] `tests/__tests__/sample.js`
- [x] `tests/__tests__/verify-eslint-config.js`
