### ISSUE TITLE
🧹 Brush up exempted file for `line-comment-position`

### ISSUE THREAD

**Issue by StewEucen** [StewEucen/eslint-config#95]
## Overview

* Brush up exempted file for `line-comment-position`

## Tasks

- [x] `Alpha value` → `above line comment`
- [x] `Beta value` → `beside line comment`
- [x] Add `eslint-disable-next-line` above
- [x] ~Add `eslint-disable-line` beside~
